class Labels:
    ASSISTANT_EXISTS = "Assistant already exists."
    ASSISTANT_REGISTERED = "Assistant successfully registered."
    DEFAULT = "default"
    DEFAULT_INSTRUCTIONS = "Answer in markdown format."
    EXITING = "Exiting..."
    INTRO = "Type 'help' or '?' for more information."
    MODEL_EXISTS = "Model already exists."
    MODEL_REGISTERED = "Model successfully registered."
    NO_ASSISTANTS = "No assistants found."
    NO_MODELS = "No models found."
    NO_PROVIDERS = "No providers found."
    PLEASE_REGISTER = "Please register."
    PROVIDER_EXISTS = "Provider already exists."
    PROVIDER_REGISTERED = "Provider successfully registered."
    REGISTERED = "registered"
    TITLE = "SEEKS"
